// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using emigrant.App.Persistencia;

namespace emigrant.App.Persistencia.Migrations
{
    [DbContext(typeof(AppContext))]
    partial class AppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("emigrant.App.Dominio.AmigoFamiliar", b =>
                {
                    b.Property<int>("AmigoFamiliarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FamAmigId")
                        .HasColumnType("int");

                    b.Property<int?>("MigranteId")
                        .HasColumnType("int");

                    b.HasKey("AmigoFamiliarId");

                    b.HasIndex("MigranteId");

                    b.ToTable("AmigoFamiliars");
                });

            modelBuilder.Entity("emigrant.App.Dominio.Migrante", b =>
                {
                    b.Property<int>("MigranteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CiudadResidencia")
                        .HasColumnType("int");

                    b.Property<string>("DireccionActual")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DirrecionElectronica")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FechaNacimiento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroDocumento")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NumeroTelefono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PaisOrigen")
                        .HasColumnType("int");

                    b.Property<bool>("SituacionLaboral")
                        .HasColumnType("bit");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MigranteId");

                    b.HasIndex("NumeroDocumento")
                        .IsUnique();

                    b.ToTable("Migrantes");
                });

            modelBuilder.Entity("emigrant.App.Dominio.AmigoFamiliar", b =>
                {
                    b.HasOne("emigrant.App.Dominio.Migrante", "Migrante")
                        .WithMany("AmigoFamiliar")
                        .HasForeignKey("MigranteId");

                    b.Navigation("Migrante");
                });

            modelBuilder.Entity("emigrant.App.Dominio.Migrante", b =>
                {
                    b.Navigation("AmigoFamiliar");
                });
#pragma warning restore 612, 618
        }
    }
}
